values = input("Enter values (separated with commas): ")
tuplelist = tuple(map(int, values.split(",")))
print("~~~~~~~~~~~~~~~~~~~~~~")
print("Values stored in tuple")
print('Tuple : ',tuplelist)
print("~~~~~~~~~~~~~~~~~~~~~~")
total = sum(tuplelist)
maxi = max(tuplelist)
mini = min(tuplelist)
print("Total: ",total)
print("Maximum: ",maxi)
print("Minimum: ",mini)
print("~~~~~~~~~~~~~~~~~~~~~~")
n = int(input("Enter an integer: "))
count = tuplelist.count(n)
print(n,"appeared",count,"times in the tuple list")